server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/speed4z/hotel-rating-config-service
          clone-on-start: true